- hosts: web1 web2
  tasks:
    - include: 'tasks/install_epel_release.yml'
    - include: 'tasks/upload_hosts_file.yml'
    - include: 'tasks/install_nginx.yml'
    - yum: name=tomcat-webapps state=installed
    - yum: name=tomcat-admin-webapps state=installed
    - include: 'tasks/install_tomcat.yml'
